[package]
name = "rusty_hg_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
rfd = "0.10.0"
egui = "0.18.0"
image = "0.24.2"
walkdir = "2.3.2"
thiserror = "1.0.32"